### ISSUE TITLE
Only works with atom beta 1.19.3, not stable 1.19.0

### ISSUE THREAD

**Issue by Aarbel** [germtb/atom-jump-block#1]
Hi @germtb , could you make it work with standard version of Atom ? Thanks ! 

![image](https://user-images.githubusercontent.com/25119847/29713958-4a1aa08c-89a1-11e7-9c84-9b97bc587940.png)

**Comment by germtb** [comment]
@Aarbel as of today (I am using 1.24.0) it seems to be working, sorry I didn't fix it in the right time. I am closing this unless the issue reappears.
